{{- if .Values.global.cloudSql.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.cloudSql.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: cloudsql-client
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.global.cloudSql.serviceAccount.gsaEmail | quote }}
{{- end }}
