{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: api-asm-plus
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default":"api-asm-plus-backend"}'
  labels:
    app.kubernetes.io/name: api-asm-plus
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: document-management-api
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: api-asm-plus
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.port | default 3000 }}
      targetPort: http
{{- end }}
